### PR TITLE
fix(epoch): now epoch api supports slot

### PR DESCRIPTION
**Pull request by rahil471**
Added slot that was missing in paths. 
Fixed path to concat string rather than replace.

### CODE REVIEW

**Comment by rahil471** [comment]
@funador Hey, please review this merge and publish a new version of npm asap. Coz I gotta use this in my project on urgent basis. 

Else I will have to publish another package.
Thanks.

**Comment by funador** [comment]
Hi rahil471 I think what you are trying to fix here is already in place unless I am missing something. This is the documentation for the endpoint: https://cardanodocs.com/technical/explorer/api/#path--api-epochs--epoch---slot- and "slot" it is listed as a param (not a path) here: https://github.com/funador/cardano-api/blob/master/lib/config.js#L37 the package works as expected based on the current api docs. 

Let me know if I am missing something here, but it seems to be fine as is.

**Comment by rahil471** [comment]
Umm I think slot is listed as a path. Can you run you code and check once. 

I'm pretty sure when I tried earlier in the day, even after passing 'slot' the results returned were for /epoch/{epoch} instead of /epoch/{epoch}/{slot}

Sorry for my bad formatting I'm replying from my cell phone.

**Comment by funador** [comment]
Just tested it works exactly as expected.  I think there might be some confusion as a result of the readme as it does not list both '/api/epochs/{epoch}' and ' /api/epochs/{epoch}/{slot}' as separate endpoints.  Will update the readme to reflect that.

**Comment by rahil471** [comment]
Okay I'll check it once tomorrow morning. 

```
if (match) {
        path = `/${query[key]}`
        delete query[key]
      }
```

I don't see this peice working with multiple paths.

**Comment by rahil471** [comment]
It's like basically we are overwriting the path instead of concatenating it.

**Comment by rahil471** [comment]
Also if `slot` is not in the paths under config. 

How can this work? 
`const match = paths.includes(key)`

Are you sure you are referring the master branch?

**Comment by funador** [comment]
Ah ok, now I see what you are looking at.  Very much a bug.  Have you run the tests before submitting the PR?

**Comment by rahil471** [comment]
Yes. All passed.

**Comment by funador** [comment]
merged and published

**Pull request merged**
